#!/bin/bash

# Prints out battery percentage

CHARGING_ICON=' '
#DISCHARGING_ICON='-'
WARNING_ICON=' '
BATTERY_FULL_ICON=''
BATTERY_2_ICON=''
BATTERY_3_ICON=''
BATTERY_4_ICON=''
ICON_CON="$HOME/.icons/myicons/battery.png"

FULL_AT=98

BAT_ICON=""
ICON=""

get_battery()
{
	# The vast majority of people only use one battery.

	if [ -d /sys/class/power_supply/BAT0 ]; then
		capacity=$(cat /sys/class/power_supply/BAT0/capacity)
		charging=$(cat /sys/class/power_supply/BAT0/status)
        if [[ "$charging" == "Charging" ]]; then
			ICON="$CHARGING_ICON"
       # elif [[ "$charging" == "Discharging" ]]; then
        #    ICON="$DISCHARGING_ICON"
        elif [[ $capacity -le 20 ]]; then
            notify-send -i $ICON_CON "Battery" "Battery low dude!!!!" -t 2000;
			ICON="$WARNING_ICON"
		fi

		if [[ $capacity -ge $FULL_AT ]]; then
			BAT_ICON=$BATTERY_FULL_ICON
		elif [[ $capacity -le 25 ]]; then
			BAT_ICON=$BATTERY_4_ICON
		elif [[ $capacity -le 60 ]]; then
			BAT_ICON=$BATTERY_3_ICON
		elif [[ $capacity -le $FULL_AT ]]; then
			BAT_ICON=$BATTERY_2_ICON
		fi
	fi
	echo "$ICON$BAT_ICON  $capacity%"
	#echo "[BAT $capacity%]"
}

get_battery
