#!/bin/bash

# A dwm_bar module to display the current backlight brighness with xbacklight
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Dependencies: light

dwm_light () {
    printf "%s %.0f%s\n" "$SEP1" "$(light)" "$SEP2"
}

dwm_light
